---
driver:
  name: ec2
  region: us-west-2
  subnet_id: subnet-ff11399b
  security_group_ids:
  aws_ssh_key_id: key-pair-561
  tags:
    Owner: nikhil.araga
    Environment: Testing
    Project: reandeploy
transport:
  ssh_key: /home/ec2-user/key-pair-561.pem
verifier:
  name: inspec
platforms:
  # Ubuntu trusty
  - name: ubuntu-14.04
    driver:
      instance_type: t2.micro
      tags:
        Name: pri-ssm-test-ubuntu-1404
suites:
  - name: default
    sudo: true
    run_list:
      - recipe[ssm::default]
