---
driver:
  name: ec2
  aws_ssh_key_id: key-pair-561
  region: us-west-2
  availability_zone: a
  subnet_id: subnet-32b27954
  instance_type: t2.micro
  image_id: ami-aa5ebdd2
  security_group_ids: sg-2a577050

provisioner:
  name: chef_zero

verifier:
  name: inspec
transport:
 ssh_key: /home/ec2-user/key-pair-561.pem

platforms:
   - name: amazon-linux

suites:
  - name: default
    sudo: true
    run_list:
      - recipe[ssm::default]
